import React from 'react'
import type { ProcurementRecord } from '@/types/procurement.types'
import { Card } from '@/components/ui/Card'
import { StatusPill } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { FileDown, Printer, ShieldCheck } from 'lucide-react'

interface FarmerPaymentsProps {
  records: ProcurementRecord[]
}

const escapeHtml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('\"', '&quot;')
    .replaceAll("'", '&#039;')

const buildReceiptHtml = (record: ProcurementRecord) => {
  const dateText = new Date(record.createdAt).toLocaleString('en-IN')
  const paymentText = record.paymentStatus === 'credited'
    ? 'Payment Credited'
    : record.paymentStatus === 'processing'
      ? 'Payment Processing'
      : record.paymentStatus === 'rejected'
        ? 'Payment Rejected'
        : 'Payment Pending'

  return `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Mandi Setu Receipt - ${escapeHtml(record.bookingNumber)}</title>
        <style>
          body{font-family:Arial,Helvetica,sans-serif;background:#f1f5f9;margin:0;padding:32px;color:#0f172a} 
          .receipt{max-width:760px;margin:0 auto;background:#fff;border:1px solid #dbe3ea;border-radius:18px;padding:34px;box-shadow:0 8px 30px rgba(15,23,42,.08)}
          .header{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #e2e8f0;padding-bottom:18px;margin-bottom:22px}
          .brand{font-size:24px;font-weight:900;letter-spacing:.06em}.muted{color:#64748b;font-size:12px}
          .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:18px}.item{border:1px solid #e2e8f0;border-radius:12px;padding:12px}.label{font-size:10px;text-transform:uppercase;color:#64748b;font-weight:700}.value{font-size:14px;font-weight:800;margin-top:5px}
          table{width:100%;border-collapse:collapse;margin:18px 0} th,td{padding:11px 8px;border-bottom:1px solid #e2e8f0;text-align:left;font-size:13px}th{color:#64748b;font-size:10px;text-transform:uppercase}
          .total{display:flex;justify-content:space-between;padding:16px 0;border-top:2px solid #0f172a;font-size:18px;font-weight:900}.status{display:inline-block;padding:7px 10px;border-radius:999px;background:#ecfdf5;color:#047857;font-weight:800;font-size:11px}
          .footer{margin-top:26px;padding-top:16px;border-top:1px dashed #cbd5e1;color:#64748b;font-size:11px;line-height:1.6}
          @media print{body{background:#fff;padding:0}.receipt{box-shadow:none;border:none;max-width:none}}
        </style>
      </head>
      <body>
        <div class="receipt">
          <div class="header">
            <div><div class="brand">MANDI SETU</div><div class="muted">Digital Procurement Receipt</div></div>
            <div style="text-align:right"><span class="status">${escapeHtml(paymentText)}</span><div class="muted" style="margin-top:7px">Receipt ID: ${escapeHtml(record.id)}</div></div>
          </div>

          <div class="grid">
            <div class="item"><div class="label">Farmer</div><div class="value">${escapeHtml(record.farmerName)}</div></div>
            <div class="item"><div class="label">Booking</div><div class="value">${escapeHtml(record.bookingNumber)}</div></div>
            <div class="item"><div class="label">Commodity</div><div class="value">${escapeHtml(record.commodityName)}</div></div>
            <div class="item"><div class="label">Quality</div><div class="value">${escapeHtml(record.qualityGrade)}</div></div>
          </div>

          <table>
            <thead><tr><th>Measurement</th><th>Value</th></tr></thead>
            <tbody>
              <tr><td>Gross Weight</td><td>${record.grossWeightKg.toLocaleString('en-IN')} kg</td></tr>
              <tr><td>Tare Weight</td><td>${record.tareWeightKg.toLocaleString('en-IN')} kg</td></tr>
              <tr><td>Net Weight</td><td>${record.netWeightKg.toLocaleString('en-IN')} kg</td></tr>
              <tr><td>Moisture</td><td>${record.moisturePercentage}%</td></tr>
              <tr><td>Moisture Deduction</td><td>${record.deductionKg.toLocaleString('en-IN')} kg</td></tr>
              <tr><td>Final Accepted Quantity</td><td>${record.finalAcceptedQuintals.toFixed(2)} Qtl</td></tr>
              <tr><td>MSP Rate</td><td>₹${record.ratePerQuintal.toLocaleString('en-IN')} / Qtl</td></tr>
            </tbody>
          </table>

          <div class="total"><span>Total Procurement Value</span><span>₹${record.totalPayableAmount.toLocaleString('en-IN')}</span></div>
          ${record.paymentUtr ? `<div class="item"><div class="label">Payment Reference</div><div class="value">${escapeHtml(record.paymentUtr)}</div></div>` : ''}

          <div class="footer">
            Generated by Mandi Setu on ${escapeHtml(dateText)}. This digital receipt reflects the procurement record stored for this booking.
            <br/>Use the browser print dialog to save a PDF copy.
          </div>
        </div>
      </body>
    </html>
  `
}

const openPrintableReceipt = (record: ProcurementRecord) => {
  const receiptWindow = window.open('', '_blank', 'width=820,height=920')

  if (!receiptWindow) {
    window.alert('Please allow pop-ups to print the receipt.')
    return
  }

  const html = buildReceiptHtml(record).replace(
    '</body>',
    '<script>window.addEventListener(\'load\', () => { window.print(); });</script></body>'
  )

  receiptWindow.document.write(html)
  receiptWindow.document.close()
  receiptWindow.focus()
}

const downloadReceipt = (record: ProcurementRecord) => {
  const blob = new Blob([buildReceiptHtml(record)], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `Mandi-Setu-Receipt-${record.bookingNumber}.html`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export const FarmerPayments: React.FC<FarmerPaymentsProps> = ({ records }) => {
  const totalAmount = records.reduce((acc, r) => acc + r.totalPayableAmount, 0)
  const totalQuintals = records.reduce((acc, r) => acc + r.finalAcceptedQuintals, 0)
  const creditedAmount = records
    .filter((r) => r.paymentStatus === 'credited')
    .reduce((acc, r) => acc + r.totalPayableAmount, 0)

  return (
    <div className="space-y-5 pb-24 max-w-xl mx-auto">
      {/* Earnings Overview Card */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-950 rounded-3xl p-6 text-white shadow-md">
        <div className="flex items-center justify-between mb-4">
          <span className="text-xs uppercase font-bold tracking-wider text-emerald-400">
            Direct Benefit Transfer (DBT)
          </span>
          <span className="inline-flex items-center gap-1 text-[11px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
            <ShieldCheck className="w-3.5 h-3.5" />
            PFMS Verified
          </span>
        </div>

        <h2 className="text-3xl font-black font-mono tracking-tight text-white">
          ₹{totalAmount.toLocaleString('en-IN')}
        </h2>
        <p className="text-xs text-slate-400 mt-1">
          Total Govt MSP procurement value generated
        </p>

        <div className="mt-5 pt-4 border-t border-slate-700/60 grid grid-cols-2 gap-3 text-xs">
          <div>
            <span className="text-slate-400 block text-[10px] uppercase">Bank Credited</span>
            <span className="font-mono font-bold text-emerald-400 text-sm">
              ₹{creditedAmount.toLocaleString('en-IN')}
            </span>
          </div>

          <div>
            <span className="text-slate-400 block text-[10px] uppercase">Total Grain Delivered</span>
            <span className="font-bold text-white text-sm">
              {totalQuintals.toFixed(2)} Quintals
            </span>
          </div>
        </div>
      </div>

      {/* Procurement Slips List */}
      <div className="space-y-3">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
            Procurement & Weighment Receipts ({records.length})
          </h3>
        </div>

        {records.length === 0 ? (
          <div className="text-center py-12 bg-white rounded-2xl border border-slate-200 text-slate-400 text-xs">
            No procurement receipts issued yet. Receipts appear automatically after weighbridge verification.
          </div>
        ) : (
          records.map((record) => (
            <Card key={record.id} className="p-4 border-slate-200">
              <div className="flex items-start justify-between gap-2 pb-3 border-b border-slate-100">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-900 text-sm">
                      {record.commodityName}
                    </span>
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-100 font-semibold text-slate-600">
                      {record.qualityGrade}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-500 font-mono mt-0.5">
                    Slip: {record.bookingNumber} • {new Date(record.createdAt).toLocaleDateString()}
                  </p>
                </div>

                <StatusPill paymentStatus={record.paymentStatus} />
              </div>

              {/* Weight Breakdown */}
              <div className="grid grid-cols-3 gap-2 py-3 border-b border-slate-100 text-xs">
                <div>
                  <span className="text-slate-400 text-[10px] block">Gross Weight</span>
                  <span className="font-mono font-bold text-slate-700">
                    {record.grossWeightKg.toLocaleString()} kg
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Tare (Vehicle)</span>
                  <span className="font-mono font-bold text-slate-700">
                    {record.tareWeightKg.toLocaleString()} kg
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Net Procured</span>
                  <span className="font-mono font-bold text-emerald-800">
                    {record.finalAcceptedQuintals} Qtl
                  </span>
                </div>
              </div>

              {/* Moisture and Rate */}
              <div className="flex items-center justify-between pt-3 text-xs">
                <div>
                  <span className="text-[10px] text-slate-400 block">Moisture: {record.moisturePercentage}%</span>
                  <span className="font-mono font-bold text-slate-700">
                    Rate: ₹{record.ratePerQuintal}/Qtl
                  </span>
                </div>

                <div className="text-right">
                  <span className="text-[10px] text-slate-400 block uppercase font-bold">Total Amount</span>
                  <span className="text-base font-black text-emerald-800 font-mono">
                    ₹{record.totalPayableAmount.toLocaleString('en-IN')}
                  </span>
                </div>
              </div>

              {/* Bank UTR Ref */}
              {record.paymentUtr && (
                <div className="mt-3 p-2 bg-slate-50 rounded-lg text-[10px] font-mono text-slate-600 flex items-center justify-between">
                  <span>UTR: {record.paymentUtr}</span>
                  <span className="text-emerald-700 font-bold">Direct Benefit Transfer</span>
                </div>
              )}

              <div className="mt-4 flex items-center justify-end gap-2">
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => openPrintableReceipt(record)}
                  leftIcon={<Printer className="w-3.5 h-3.5" />}
                >
                  Print / Save PDF
                </Button>
                <button
                  type="button"
                  onClick={() => downloadReceipt(record)}
                  className="inline-flex items-center gap-1.5 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800 hover:bg-emerald-100"
                >
                  <FileDown className="w-3.5 h-3.5" />
                  Download Digital Receipt
                </button>
              </div>
            </Card>
          ))
        )}
      </div>
    </div>
  )
}
